import type { NoteTopicMeta, NoteKitData } from '@/lib/notes/types'
import { OBJECTIVES_RESOLUTION_KIT } from '@/lib/notes/content/objectives-resolution-article-2a'
import { CONSTITUTION_1973_KIT } from '@/lib/notes/content/constitution-1973'
import { EIGHTEENTH_AMENDMENT_KIT } from '@/lib/notes/content/eighteenth-amendment'
import { LAHORE_RESOLUTION_KIT } from '@/lib/notes/content/lahore-resolution-1940'
import { IDEOLOGY_OF_PAKISTAN_KIT } from '@/lib/notes/content/ideology-of-pakistan'
import { CIVIL_MILITARY_RELATIONS_KIT } from '@/lib/notes/content/civil-military-relations'
import { FOREIGN_POLICY_POST_911_KIT } from '@/lib/notes/content/foreign-policy-post-911'
import { PAKISTAN_INDIA_RELATIONS_KIT } from '@/lib/notes/content/pakistan-india-relations'
import { POLITICAL_EVOLUTION_1971_KIT } from '@/lib/notes/content/political-evolution-1971'
import { DEMOCRACY_EVOLUTION_PAKISTAN_KIT } from '@/lib/notes/content/democracy-evolution-pakistan'
import { CONSTITUTIONAL_DEVELOPMENT_PAKISTAN_KIT } from '@/lib/notes/content/constitutional-development-pakistan'
import { LAND_PEOPLE_PAKISTAN_KIT } from '@/lib/notes/content/land-people-pakistan'
import { INDUS_RIVER_SYSTEM_KIT } from '@/lib/notes/content/indus-river-system'
import { PAKISTAN_NUCLEAR_PROGRAM_KIT } from '@/lib/notes/content/pakistan-nuclear-program'
import { CPEC_REGIONAL_CONNECTIVITY_KIT } from '@/lib/notes/content/cpec-and-regional-connectivity'
import { PAKISTAN_ECONOMY_IMF_SBP_KIT } from '@/lib/notes/content/pakistan-economy-imf-sbp'
import { CLIMATE_FLOODS_SMOG_PAKISTAN_KIT } from '@/lib/notes/content/climate-floods-smog-pakistan'
import { PILLARS_OF_ISLAM_KIT } from '@/lib/notes/content/pillars-of-islam'
import { SOURCES_OF_ISLAMIC_LAW_KIT } from '@/lib/notes/content/sources-of-islamic-law'
import { QURAN_REVELATION_COMPILATION_KIT } from '@/lib/notes/content/quran-revelation-compilation'
import { SEERAH_HIGH_YIELD_KIT } from '@/lib/notes/content/seerah-high-yield'
import { HADITH_SCIENCES_BASICS_KIT } from '@/lib/notes/content/hadith-sciences-basics'
import { ENGLISH_ESSAY_CSS_KIT } from '@/lib/notes/content/english-essay-css'
import { PRECIS_COMPOSITION_CSS_KIT } from '@/lib/notes/content/precis-composition-css'
import { ENGLISH_GRAMMAR_HIGH_YIELD_KIT } from '@/lib/notes/content/english-grammar-high-yield'
import { UN_INTERNATIONAL_ORGANIZATIONS_KIT } from '@/lib/notes/content/un-international-organizations'
import { COMPUTER_NETWORKING_BASICS_KIT } from '@/lib/notes/content/computer-networking-basics'
import { VITAMINS_HORMONES_BASICS_KIT } from '@/lib/notes/content/vitamins-hormones-basics'
import { PERCENTAGES_RATIOS_PROFIT_LOSS_KIT } from '@/lib/notes/content/percentages-ratios-profit-loss'
import { ETHICS_THEORIES_BASICS_KIT } from '@/lib/notes/content/ethics-theories-basics'
import { GOOD_GOVERNANCE_UNDP_KIT } from '@/lib/notes/content/good-governance-undp'
import { SDGS_PAKISTAN_KIT } from '@/lib/notes/content/sdgs-pakistan'
import { HUMAN_RIGHTS_UDHR_KIT } from '@/lib/notes/content/human-rights-udhr'
import { ALLAMA_IQBAL_ALLAHABAD_KIT } from '@/lib/notes/content/allama-iqbal-allahabad'
import { ARTICLES_OF_FAITH_ISLAM_KIT } from '@/lib/notes/content/articles-of-faith-islam'
import { CLIMATE_CHANGE_PAKISTAN_POLICY_KIT } from '@/lib/notes/content/climate-change-pakistan-policy'
import { EDUCATION_SYSTEM_PAKISTAN_KIT } from '@/lib/notes/content/education-system-pakistan'
import { ENGLISH_VOCABULARY_HIGH_YIELD_KIT } from '@/lib/notes/content/english-vocabulary-high-yield'
import { EVERYDAY_SCIENCE_CHEMISTRY_BASICS_KIT } from '@/lib/notes/content/everyday-science-chemistry-basics'
import { EVERYDAY_SCIENCE_PHYSICS_BASICS_KIT } from '@/lib/notes/content/everyday-science-physics-basics'
import { FEDERATION_PROVINCIAL_AUTONOMY_KIT } from '@/lib/notes/content/federation-provincial-autonomy'
import { HUMAN_RIGHTS_IN_ISLAM_KIT } from '@/lib/notes/content/human-rights-in-islam'
import { ISLAMIC_CIVILIZATION_CONTRIBUTIONS_KIT } from '@/lib/notes/content/islamic-civilization-contributions'
import { KASHMIR_DISPUTE_BASICS_KIT } from '@/lib/notes/content/kashmir-dispute-basics'
import { LIFE_OF_PROPHET_MADINAH_PERIOD_KIT } from '@/lib/notes/content/life-of-prophet-madinah-period'
import { LIFE_OF_PROPHET_MAKKAH_PERIOD_KIT } from '@/lib/notes/content/life-of-prophet-makkah-period'
import { OIC_SAARC_SCO_KIT } from '@/lib/notes/content/oic-saarc-sco'
import { PAKISTAN_CHINA_RELATIONS_KIT } from '@/lib/notes/content/pakistan-china-relations'
import { PAKISTAN_FOREIGN_POLICY_PRINCIPLES_KIT } from '@/lib/notes/content/pakistan-foreign-policy-principles'
import { PAKISTAN_MOVEMENT_1857_1947_KIT } from '@/lib/notes/content/pakistan-movement-1857-1947'
import { PHYSICAL_GEOGRAPHY_PAKISTAN_KIT } from '@/lib/notes/content/physical-geography-pakistan'
import { POPULATION_DEMOGRAPHICS_PAKISTAN_KIT } from '@/lib/notes/content/population-demographics-pakistan'
import { PUBLIC_SERVICE_VALUES_KIT } from '@/lib/notes/content/public-service-values'
import { QUAID_E_AZAM_POLITICAL_LEADERSHIP_KIT } from '@/lib/notes/content/quaid-e-azam-political-leadership'
import { SENTENCE_CORRECTION_METHOD_KIT } from '@/lib/notes/content/sentence-correction-method'
import { SEPARATION_OF_POWERS_PAKISTAN_KIT } from '@/lib/notes/content/separation-of-powers-pakistan'
import { SOCIAL_PROBLEMS_PAKISTAN_KIT } from '@/lib/notes/content/social-problems-pakistan'
import { TWO_NATION_THEORY_KIT } from '@/lib/notes/content/two-nation-theory'
import { WORLD_PHYSICAL_GEOGRAPHY_BASICS_KIT } from '@/lib/notes/content/world-physical-geography-basics'
import { LOCAL_GOVERNMENT_PAKISTAN_KIT } from '@/lib/notes/content/local-government-pakistan'
import { MEDIA_CIVIL_SOCIETY_PAKISTAN_KIT } from '@/lib/notes/content/media-and-civil-society-pakistan'
import { NFC_AWARD_FISCAL_FEDERALISM_KIT } from '@/lib/notes/content/nfc-award-fiscal-federalism'
import { WOMEN_EMPOWERMENT_PAKISTAN_KIT } from '@/lib/notes/content/women-empowerment-pakistan'
import { ENERGY_CRISIS_PAKISTAN_KIT } from '@/lib/notes/content/energy-crisis-pakistan'
import { WATER_CRISIS_PAKISTAN_KIT } from '@/lib/notes/content/water-crisis-pakistan'
import { BUREAUCRACY_REFORM_PAKISTAN_KIT } from '@/lib/notes/content/bureaucracy-reform-pakistan'
import { JUDICIARY_PAKISTAN_BASICS_KIT } from '@/lib/notes/content/judiciary-pakistan-basics'
import { ENGLISH_IDIOMS_ONE_PAPER_KIT } from '@/lib/notes/content/english-idioms-one-paper'
import { SET_THEORY_BASICS_MATH_KIT } from '@/lib/notes/content/set-theory-basics-math'
import { AGRICULTURE_PAKISTAN_KIT } from '@/lib/notes/content/agriculture-pakistan'
import { INDUSTRY_TRADE_PAKISTAN_KIT } from '@/lib/notes/content/industry-and-trade-pakistan'
import { TERRORISM_EXTREMISM_PAKISTAN_KIT } from '@/lib/notes/content/terrorism-extremism-pakistan'
import { AFGHANISTAN_PAKISTAN_RELATIONS_KIT } from '@/lib/notes/content/afghanistan-pakistan-relations'
import { MUSLIM_WORLD_PAKISTAN_KIT } from '@/lib/notes/content/muslim-world-pakistan'
import { ENVIRONMENTAL_POLLUTION_PAKISTAN_KIT } from '@/lib/notes/content/environmental-pollution-pakistan'
import { COMPARATIVE_RELIGIONS_BASICS_KIT } from '@/lib/notes/content/comparative-religions-basics'
import { ZAKAT_SYSTEM_SOCIAL_WELFARE_KIT } from '@/lib/notes/content/zakat-system-social-welfare'
import { ESSAY_OUTLINING_WORKSHOP_KIT } from '@/lib/notes/content/essay-outlining-workshop'
import { COMPREHENSION_PASSAGE_METHOD_KIT } from '@/lib/notes/content/comprehension-passage-method'
import { CONSTITUTION_FUNDAMENTAL_RIGHTS_KIT } from '@/lib/notes/content/constitution-fundamental-rights'
import { CONSTITUTION_PRINCIPLES_POLICY_KIT } from '@/lib/notes/content/constitution-principles-policy'
import { ISLAMIC_PROVISIONS_1973_KIT } from '@/lib/notes/content/islamic-provisions-1973'
import { BUDGET_FISCAL_POLICY_PAKISTAN_KIT } from '@/lib/notes/content/budget-fiscal-policy-pakistan'
import { INFLATION_MONETARY_POLICY_KIT } from '@/lib/notes/content/inflation-monetary-policy'
import { UN_SECURITY_COUNCIL_PEACEKEEPING_KIT } from '@/lib/notes/content/un-security-council-peacekeeping'
import { WORLD_ORGANIZATIONS_IMF_WB_WTO_KIT } from '@/lib/notes/content/world-organizations-imf-wb-wto'
import { BIOLOGY_HUMAN_SYSTEMS_KIT } from '@/lib/notes/content/biology-human-systems'
import { COMPUTER_HARDWARE_BASICS_KIT } from '@/lib/notes/content/computer-hardware-basics'
import { RATIO_PROPORTION_AVERAGES_KIT } from '@/lib/notes/content/ratio-proportion-averages'
import { LANGUAGE_POLICY_PAKISTAN_KIT } from '@/lib/notes/content/language-policy-pakistan'
import { CULTURAL_HERITAGE_PAKISTAN_KIT } from '@/lib/notes/content/cultural-heritage-pakistan'
import { HEALTH_SYSTEM_PAKISTAN_KIT } from '@/lib/notes/content/health-system-pakistan'
import { URBANIZATION_HOUSING_PAKISTAN_KIT } from '@/lib/notes/content/urbanization-housing-pakistan'
import { DISASTER_MANAGEMENT_PAKISTAN_KIT } from '@/lib/notes/content/disaster-management-pakistan'
import { PAKISTAN_USA_RELATIONS_KIT } from '@/lib/notes/content/pakistan-usa-relations'
import { SAARC_REGIONAL_COOPERATION_KIT } from '@/lib/notes/content/saarc-regional-cooperation'
import { HAJJ_UMRAH_FIQH_BASICS_KIT } from '@/lib/notes/content/hajj-umrah-fiqh-basics'
import { RAMADAN_FASTING_RULES_KIT } from '@/lib/notes/content/ramadan-fasting-rules'
import { ENGLISH_PUNCTUATION_CAPITALIZATION_KIT } from '@/lib/notes/content/english-punctuation-capitalization'
import { PERCENTAGES_APPLICATIONS_EXAM_KIT } from '@/lib/notes/content/percentages-applications-exam'
import { BOOLEAN_LOGIC_NUMBER_SYSTEMS_KIT } from '@/lib/notes/content/boolean-logic-number-systems'
import { BALOCHISTAN_ISSUES_EXAM_KIT } from '@/lib/notes/content/balochistan-issues-exam'
import { KARACHI_URBAN_GOVERNANCE_KIT } from '@/lib/notes/content/karachi-urban-governance'
import { CPEC_GWADAR_DEEP_DIVE_KIT } from '@/lib/notes/content/cpec-gwadar-deep-dive'
import { INDUS_WATERS_TREATY_DEEP_KIT } from '@/lib/notes/content/indus-waters-treaty-deep'
import { PAKISTAN_IRAN_RELATIONS_KIT } from '@/lib/notes/content/pakistan-iran-relations'
import { PAKISTAN_SAUDI_RELATIONS_KIT } from '@/lib/notes/content/pakistan-saudi-relations'
import { ISLAMIC_ECONOMIC_SYSTEM_KIT } from '@/lib/notes/content/islamic-economic-system'
import { STATUS_OF_WOMEN_IN_ISLAM_KIT } from '@/lib/notes/content/status-of-women-in-islam'
import { TRANSLATION_URDU_ENGLISH_METHOD_KIT } from '@/lib/notes/content/translation-urdu-english-method'
import { PROBABILITY_BASICS_EXAM_KIT } from '@/lib/notes/content/probability-basics-exam'

const TOPICS: NoteTopicMeta[] = [
  // ── Pakistan Affairs / Pakistan Studies ─────────────────────────────
  {
    slug: 'objectives-resolution-article-2a',
    title: 'Objectives Resolution and Article 2A',
    shortTitle: 'Objectives Resolution',
    contentId: 'objectives-resolution-article-2a',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'objectives resolution',
      'article 2a',
      'constitutional history',
      'constitutional development',
      'ideology of pakistan',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'constitution',
  },
  {
    slug: 'constitution-1973',
    title: '1973 Constitution of Pakistan',
    shortTitle: '1973 Constitution',
    contentId: 'constitution-1973',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      '1973 constitution',
      'constitutions of pakistan',
      'parliamentary system',
      'political evolution since 1971',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'constitution',
  },
  {
    slug: 'eighteenth-amendment',
    title: '18th Amendment (2010)',
    shortTitle: '18th Amendment',
    contentId: 'eighteenth-amendment',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      '18th amendment',
      'eighteenth amendment',
      'provincial autonomy',
      'federalism',
      'constitutional amendments',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'constitution',
  },
  {
    slug: 'constitution-fundamental-rights',
    title: 'Fundamental Rights (Articles 8-28)',
    shortTitle: 'Fundamental Rights',
    contentId: 'constitution-fundamental-rights',
    subjectSlugs: ['pakistan-affairs', 'ethics-civics'],
    syllabusHints: [
      'fundamental rights',
      'articles 8-28',
      '1973 constitution',
      'human rights pakistan',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'constitution',
  },
  {
    slug: 'constitution-principles-policy',
    title: 'Principles of Policy (Articles 29-40)',
    shortTitle: 'Principles of Policy',
    contentId: 'constitution-principles-policy',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'principles of policy',
      'articles 29-40',
      '1973 constitution',
      'social justice',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'constitution',
  },
  {
    slug: 'islamic-provisions-1973',
    title: 'Islamic Provisions in the 1973 Constitution',
    shortTitle: 'Islamic Provisions 1973',
    contentId: 'islamic-provisions-1973',
    subjectSlugs: ['pakistan-affairs', 'islamic-studies'],
    syllabusHints: [
      'islamic provisions',
      'article 2',
      'article 2a',
      'article 227',
      'federal shariat court',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'constitution',
  },
  {
    slug: 'lahore-resolution-1940',
    title: 'Lahore Resolution (Pakistan Resolution) 1940',
    shortTitle: 'Lahore Resolution',
    contentId: 'lahore-resolution-1940',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'lahore resolution',
      'pakistan resolution',
      'freedom movement',
      'ideology of pakistan',
      '1940',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'pakistan-movement',
  },
  {
    slug: 'ideology-of-pakistan',
    title: 'Ideology of Pakistan (Iqbal and Quaid)',
    shortTitle: 'Ideology of Pakistan',
    contentId: 'ideology-of-pakistan',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'ideology of pakistan',
      'iqbal',
      'quaid',
      'two-nation',
      'two nation',
      'allahabad',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'ideology',
  },
  {
    slug: 'two-nation-theory',
    title: 'Two-Nation Theory',
    shortTitle: 'Two-Nation Theory',
    contentId: 'two-nation-theory',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'two-nation theory',
      'two nation theory',
      'ideology of pakistan',
      'muslim nationalism',
      'freedom movement',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'ideology',
  },
  {
    slug: 'allama-iqbal-allahabad',
    title: 'Allama Iqbal and the Allahabad Address',
    shortTitle: 'Iqbal Allahabad Address',
    contentId: 'allama-iqbal-allahabad',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'iqbal',
      'allahabad',
      'allahabad address',
      'ideology of pakistan',
      'muslim nationalism',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'ideology',
  },
  {
    slug: 'quaid-e-azam-political-leadership',
    title: 'Quaid-e-Azam Political Leadership',
    shortTitle: 'Quaid Leadership',
    contentId: 'quaid-e-azam-political-leadership',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'quaid',
      'jinnah',
      'political leadership',
      'freedom movement',
      'ideology of pakistan',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'pakistan-movement',
  },
  {
    slug: 'pakistan-movement-1857-1947',
    title: 'Pakistan Movement Timeline (1857 to 1947)',
    shortTitle: 'Pakistan Movement',
    contentId: 'pakistan-movement-1857-1947',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'pakistan movement',
      'freedom movement',
      '1857',
      '1947',
      'ideology of pakistan',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'pakistan-movement',
  },
  {
    slug: 'constitutional-development-pakistan',
    title: 'Constitutional Development (1956, 1962, 1973)',
    shortTitle: 'Constitutional Development',
    contentId: 'constitutional-development-pakistan',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'constitutional development',
      '1956',
      '1962',
      '1973 and amendments',
      'constitutions of pakistan',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'constitution',
  },
  {
    slug: 'federation-provincial-autonomy',
    title: 'Federation and Provincial Autonomy',
    shortTitle: 'Federation and Autonomy',
    contentId: 'federation-provincial-autonomy',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'federation',
      'provincial autonomy',
      'federalism',
      'constitutional development',
      'governance',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'constitution',
  },
  {
    slug: 'civil-military-relations',
    title: 'Civil-Military Relations in Pakistan',
    shortTitle: 'Civil-Military Relations',
    contentId: 'civil-military-relations',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: ['civil-military', 'civil military', 'martial law', 'military regimes'],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'politics',
  },
  {
    slug: 'foreign-policy-post-911',
    title: 'Foreign Policy of Pakistan after 9/11',
    shortTitle: 'Foreign Policy after 9/11',
    contentId: 'foreign-policy-post-911',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: ['foreign policy', '9/11', 'post 9/11', 'afghanistan', 'war on terror'],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'foreign-policy',
  },
  {
    slug: 'pakistan-foreign-policy-principles',
    title: 'Principles of Pakistan Foreign Policy',
    shortTitle: 'FP Principles',
    contentId: 'pakistan-foreign-policy-principles',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'foreign policy',
      'principles of foreign policy',
      'international relations',
      'pakistan foreign policy',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'foreign-policy',
  },
  {
    slug: 'pakistan-india-relations',
    title: 'Pakistan-India Relations since 1947',
    shortTitle: 'Pakistan-India Relations',
    contentId: 'pakistan-india-relations',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: ['pakistan and india', 'india relations', 'kashmir', 'simla', 'indus waters'],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'foreign-policy',
  },
  {
    slug: 'kashmir-dispute-basics',
    title: 'Kashmir Dispute (Exam Basics)',
    shortTitle: 'Kashmir Dispute',
    contentId: 'kashmir-dispute-basics',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'kashmir',
      'kashmir dispute',
      'pakistan and india',
      'foreign policy',
      'un resolutions',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'foreign-policy',
  },
  {
    slug: 'pakistan-usa-relations',
    title: 'Pakistan-USA Relations',
    shortTitle: 'Pakistan-USA',
    contentId: 'pakistan-usa-relations',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'pakistan usa',
      'pakistan-us relations',
      'cold war',
      'post-9/11',
      'foreign policy',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'foreign-policy',
  },
  {
    slug: 'pakistan-china-relations',
    title: 'Pakistan-China Relations',
    shortTitle: 'Pakistan-China Relations',
    contentId: 'pakistan-china-relations',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'china',
      'pakistan china',
      'cpec',
      'foreign policy',
      'regional connectivity',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'foreign-policy',
  },
  {
    slug: 'pakistan-iran-relations',
    title: 'Pakistan-Iran Relations',
    shortTitle: 'Pakistan-Iran',
    contentId: 'pakistan-iran-relations',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'pakistan iran',
      'iran relations',
      'border trade',
      'energy pipeline',
      'foreign policy',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'foreign-policy',
  },
  {
    slug: 'pakistan-saudi-relations',
    title: 'Pakistan-Saudi Arabia Relations',
    shortTitle: 'Pakistan-Saudi',
    contentId: 'pakistan-saudi-relations',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'pakistan saudi',
      'saudi arabia',
      'hajj',
      'remittances',
      'muslim world',
      'foreign policy',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'foreign-policy',
  },
  {
    slug: 'political-evolution-1971',
    title: 'Political Evolution since 1971',
    shortTitle: 'Politics since 1971',
    contentId: 'political-evolution-1971',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: ['political evolution since 1971', 'since 1971', 'bhutto', 'zia', 'musharraf'],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'politics',
  },
  {
    slug: 'democracy-evolution-pakistan',
    title: 'Evolution of Democratic System in Pakistan',
    shortTitle: 'Democratic System',
    contentId: 'democracy-evolution-pakistan',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: ['evolution of democratic', 'democratic system', 'elections', 'parliamentary'],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'politics',
  },
  {
    slug: 'land-people-pakistan',
    title: 'Land and People of Pakistan',
    shortTitle: 'Land and People',
    contentId: 'land-people-pakistan',
    subjectSlugs: ['pakistan-affairs', 'geography'],
    syllabusHints: ['land and people', 'geography', 'society', 'resources', 'provinces'],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'geography',
  },
  {
    slug: 'physical-geography-pakistan',
    title: 'Physical Geography of Pakistan',
    shortTitle: 'Pakistan Physical Geography',
    contentId: 'physical-geography-pakistan',
    subjectSlugs: ['geography', 'pakistan-affairs'],
    syllabusHints: [
      'physical geography',
      'pakistan geography',
      'landforms',
      'himalayas',
      'karakoram',
    ],
    mcqSubjectSlug: 'geography',
    mcqTagHint: 'physical-geography',
  },
  {
    slug: 'indus-river-system',
    title: 'Indus River System and Water Resources',
    shortTitle: 'Indus River System',
    contentId: 'indus-river-system',
    subjectSlugs: ['pakistan-affairs', 'geography'],
    syllabusHints: ['indus', 'water', 'tarbela', 'mangla', 'indus waters treaty'],
    mcqSubjectSlug: 'geography',
    mcqTagHint: 'rivers',
  },
  {
    slug: 'indus-waters-treaty-deep',
    title: 'Indus Waters Treaty (Deep Dive)',
    shortTitle: 'Indus Waters Treaty',
    contentId: 'indus-waters-treaty-deep',
    subjectSlugs: ['pakistan-affairs', 'geography', 'current-affairs'],
    syllabusHints: [
      'indus waters treaty',
      'iwt 1960',
      'permanent indus commission',
      'water security',
      'eastern western rivers',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'water',
  },
  {
    slug: 'population-demographics-pakistan',
    title: 'Population and Demographics of Pakistan',
    shortTitle: 'Population Demographics',
    contentId: 'population-demographics-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'population',
      'demographics',
      'census',
      'social issues',
      'current affairs',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'demographics',
  },
  {
    slug: 'pakistan-nuclear-program',
    title: 'Pakistan Nuclear Program (Exam Facts)',
    shortTitle: 'Nuclear Program',
    contentId: 'pakistan-nuclear-program',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: ['nuclear', 'chagai', 'deterrence', '1998'],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'nuclear',
  },
  {
    slug: 'education-system-pakistan',
    title: 'Education System of Pakistan',
    shortTitle: 'Education System',
    contentId: 'education-system-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'education',
      'education policy',
      'social development',
      '18th amendment',
      'literacy',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'education',
  },
  {
    slug: 'language-policy-pakistan',
    title: 'Language Policy of Pakistan (Article 251)',
    shortTitle: 'Language Policy',
    contentId: 'language-policy-pakistan',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'language policy',
      'article 251',
      'urdu',
      'national language',
      'provincial languages',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'constitution',
  },
  {
    slug: 'cultural-heritage-pakistan',
    title: 'Cultural Heritage of Pakistan',
    shortTitle: 'Cultural Heritage',
    contentId: 'cultural-heritage-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'cultural heritage',
      'unesco',
      'soft power',
      'culture',
      'tourism',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'culture',
  },
  {
    slug: 'health-system-pakistan',
    title: 'Health System of Pakistan',
    shortTitle: 'Health System',
    contentId: 'health-system-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'health system',
      'lady health workers',
      'primary health care',
      'sdg 3',
      'social development',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'health',
  },
  {
    slug: 'urbanization-housing-pakistan',
    title: 'Urbanisation and Housing in Pakistan',
    shortTitle: 'Urbanisation and Housing',
    contentId: 'urbanization-housing-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'urbanisation',
      'urbanization',
      'housing',
      'katchi abadi',
      'informal settlements',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'social-issues',
  },
  {
    slug: 'karachi-urban-governance',
    title: 'Karachi Urban Governance',
    shortTitle: 'Karachi Governance',
    contentId: 'karachi-urban-governance',
    subjectSlugs: ['pakistan-affairs', 'current-affairs', 'ethics-civics'],
    syllabusHints: [
      'karachi',
      'urban governance',
      'mega city',
      'local government',
      'service delivery',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'governance',
  },
  {
    slug: 'disaster-management-pakistan',
    title: 'Disaster Management in Pakistan',
    shortTitle: 'Disaster Management',
    contentId: 'disaster-management-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs', 'geography'],
    syllabusHints: [
      'disaster management',
      'ndma',
      'pdma',
      'floods',
      'earthquake preparedness',
    ],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'disaster',
  },
  {
    slug: 'social-problems-pakistan',
    title: 'Social Problems of Pakistan (Poverty, Education, Health)',
    shortTitle: 'Social Problems',
    contentId: 'social-problems-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'social problems',
      'poverty',
      'education',
      'health',
      'contemporary issues',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'social-issues',
  },
  {
    slug: 'nfc-award-fiscal-federalism',
    title: 'NFC Award and Fiscal Federalism',
    shortTitle: 'NFC Award',
    contentId: 'nfc-award-fiscal-federalism',
    subjectSlugs: ['pakistan-affairs'],
    syllabusHints: [
      'nfc',
      'nfc award',
      'fiscal federalism',
      'resource sharing',
      'federalism',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'federalism',
  },
  {
    slug: 'local-government-pakistan',
    title: 'Local Government in Pakistan',
    shortTitle: 'Local Government',
    contentId: 'local-government-pakistan',
    subjectSlugs: ['pakistan-affairs', 'ethics-civics'],
    syllabusHints: [
      'local government',
      'devolution',
      'bd system',
      'governance',
      'federalism',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'governance',
  },
  {
    slug: 'media-and-civil-society-pakistan',
    title: 'Media and Civil Society in Pakistan',
    shortTitle: 'Media and Civil Society',
    contentId: 'media-and-civil-society-pakistan',
    subjectSlugs: ['pakistan-affairs', 'ethics-civics'],
    syllabusHints: [
      'media',
      'civil society',
      'article 19',
      'democracy',
      'human rights',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'governance',
  },
  {
    slug: 'women-empowerment-pakistan',
    title: 'Women Empowerment in Pakistan',
    shortTitle: 'Women Empowerment',
    contentId: 'women-empowerment-pakistan',
    subjectSlugs: ['pakistan-affairs', 'ethics-civics', 'current-affairs'],
    syllabusHints: [
      'women empowerment',
      'gender',
      'cedaw',
      'human rights',
      'governance',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'gender',
  },
  {
    slug: 'energy-crisis-pakistan',
    title: 'Energy Crisis in Pakistan',
    shortTitle: 'Energy Crisis',
    contentId: 'energy-crisis-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'energy crisis',
      'circular debt',
      'power generation',
      'cpec energy',
      'economy',
    ],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'energy',
  },
  {
    slug: 'water-crisis-pakistan',
    title: 'Water Crisis in Pakistan',
    shortTitle: 'Water Crisis',
    contentId: 'water-crisis-pakistan',
    subjectSlugs: ['pakistan-affairs', 'geography', 'current-affairs'],
    syllabusHints: [
      'water crisis',
      'water scarcity',
      'tarbela',
      'mangla',
      'indus waters treaty',
      'climate',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'water',
  },
  {
    slug: 'bureaucracy-reform-pakistan',
    title: 'Bureaucracy Reform in Pakistan',
    shortTitle: 'Bureaucracy Reform',
    contentId: 'bureaucracy-reform-pakistan',
    subjectSlugs: ['pakistan-affairs', 'ethics-civics'],
    syllabusHints: [
      'bureaucracy',
      'civil service',
      'public administration',
      'e-governance',
      'governance',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'governance',
  },
  {
    slug: 'judiciary-pakistan-basics',
    title: 'Judiciary in Pakistan (Basics)',
    shortTitle: 'Judiciary Basics',
    contentId: 'judiciary-pakistan-basics',
    subjectSlugs: ['pakistan-affairs', 'ethics-civics'],
    syllabusHints: [
      'judiciary',
      'supreme court',
      'high courts',
      'judicial review',
      'suo motu',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'judiciary',
  },
  {
    slug: 'agriculture-pakistan',
    title: 'Agriculture in Pakistan',
    shortTitle: 'Agriculture Pakistan',
    contentId: 'agriculture-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'agriculture',
      'crops',
      'wheat',
      'cotton',
      'irrigation',
      'rural economy',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'agriculture',
  },
  {
    slug: 'industry-and-trade-pakistan',
    title: 'Industry and Trade of Pakistan',
    shortTitle: 'Industry and Trade',
    contentId: 'industry-and-trade-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'industry',
      'trade',
      'exports',
      'remittances',
      'trade deficit',
      'textiles',
    ],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'economy',
  },
  {
    slug: 'terrorism-extremism-pakistan',
    title: 'Terrorism and Extremism in Pakistan',
    shortTitle: 'Terrorism and Extremism',
    contentId: 'terrorism-extremism-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'terrorism',
      'extremism',
      'national action plan',
      'nap',
      'internal security',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'security',
  },
  {
    slug: 'balochistan-issues-exam',
    title: 'Balochistan Issues (Exam Framing)',
    shortTitle: 'Balochistan Issues',
    contentId: 'balochistan-issues-exam',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'balochistan',
      'provincial issues',
      'gwadar',
      'resource sharing',
      'development',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'provincial-issues',
  },
  {
    slug: 'afghanistan-pakistan-relations',
    title: 'Afghanistan-Pakistan Relations',
    shortTitle: 'Afghanistan Relations',
    contentId: 'afghanistan-pakistan-relations',
    subjectSlugs: ['pakistan-affairs', 'current-affairs'],
    syllabusHints: [
      'afghanistan',
      'durand line',
      'refugees',
      'foreign policy',
      'neighbourhood',
    ],
    mcqSubjectSlug: 'pakistan-affairs',
    mcqTagHint: 'foreign-policy',
  },
  {
    slug: 'muslim-world-pakistan',
    title: 'Pakistan and the Muslim World',
    shortTitle: 'Muslim World Pakistan',
    contentId: 'muslim-world-pakistan',
    subjectSlugs: ['pakistan-affairs', 'current-affairs', 'general-knowledge'],
    syllabusHints: [
      'muslim world',
      'oic',
      'saudi arabia',
      'turkey',
      'iran',
      'ummah',
    ],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'muslim-world',
  },
  {
    slug: 'environmental-pollution-pakistan',
    title: 'Environmental Pollution in Pakistan',
    shortTitle: 'Environmental Pollution',
    contentId: 'environmental-pollution-pakistan',
    subjectSlugs: [
      'pakistan-affairs',
      'current-affairs',
      'geography',
      'everyday-science',
    ],
    syllabusHints: [
      'pollution',
      'smog',
      'air pollution',
      'water pollution',
      'solid waste',
      'environment',
    ],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'environment',
  },

  // ── Current Affairs ─────────────────────────────────────────────────
  {
    slug: 'cpec-and-regional-connectivity',
    title: 'CPEC and Regional Connectivity',
    shortTitle: 'CPEC',
    contentId: 'cpec-and-regional-connectivity',
    subjectSlugs: ['current-affairs', 'pakistan-affairs'],
    syllabusHints: ['cpec', 'belt and road', 'gwadar', 'china', 'connectivity'],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'cpec',
  },
  {
    slug: 'cpec-gwadar-deep-dive',
    title: 'CPEC Gwadar Deep Dive',
    shortTitle: 'Gwadar Deep Dive',
    contentId: 'cpec-gwadar-deep-dive',
    subjectSlugs: ['current-affairs', 'pakistan-affairs'],
    syllabusHints: [
      'gwadar',
      'gwadar port',
      'cpec sez',
      'arabian sea port',
      'balochistan coast',
    ],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'cpec',
  },
  {
    slug: 'pakistan-economy-imf-sbp',
    title: 'Pakistan Economy, IMF and SBP Basics',
    shortTitle: 'Economy, IMF and SBP',
    contentId: 'pakistan-economy-imf-sbp',
    subjectSlugs: ['current-affairs', 'pakistan-affairs'],
    syllabusHints: ['economy', 'imf', 'sbp', 'inflation', 'economic survey', 'economic conditions'],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'economy',
  },
  {
    slug: 'budget-fiscal-policy-pakistan',
    title: 'Budget and Fiscal Policy in Pakistan',
    shortTitle: 'Budget and Fiscal Policy',
    contentId: 'budget-fiscal-policy-pakistan',
    subjectSlugs: ['current-affairs', 'pakistan-affairs'],
    syllabusHints: [
      'budget',
      'fiscal policy',
      'fbr',
      'deficit',
      'taxation',
    ],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'economy',
  },
  {
    slug: 'inflation-monetary-policy',
    title: 'Inflation and Monetary Policy Basics',
    shortTitle: 'Inflation and Monetary Policy',
    contentId: 'inflation-monetary-policy',
    subjectSlugs: ['current-affairs', 'pakistan-affairs'],
    syllabusHints: [
      'inflation',
      'monetary policy',
      'sbp',
      'cpi',
      'policy rate',
    ],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'economy',
  },
  {
    slug: 'climate-floods-smog-pakistan',
    title: 'Climate Change, Floods and Smog in Pakistan',
    shortTitle: 'Climate, Floods, Smog',
    contentId: 'climate-floods-smog-pakistan',
    subjectSlugs: ['current-affairs', 'pakistan-affairs', 'everyday-science', 'geography'],
    syllabusHints: ['climate', 'floods', 'smog', 'environment', 'paris agreement', 'social problems'],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'environment',
  },
  {
    slug: 'climate-change-pakistan-policy',
    title: 'Climate Change and Pakistan Policy Response',
    shortTitle: 'Climate Policy Pakistan',
    contentId: 'climate-change-pakistan-policy',
    subjectSlugs: ['current-affairs', 'pakistan-affairs', 'geography'],
    syllabusHints: [
      'climate change',
      'climate policy',
      'environment',
      'disaster risk',
      'ndc',
    ],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'environment',
  },
  {
    slug: 'oic-saarc-sco',
    title: 'OIC, SAARC and SCO',
    shortTitle: 'OIC, SAARC, SCO',
    contentId: 'oic-saarc-sco',
    subjectSlugs: ['general-knowledge', 'current-affairs'],
    syllabusHints: [
      'oic',
      'saarc',
      'sco',
      'international organizations',
      'regional diplomacy',
    ],
    mcqSubjectSlug: 'general-knowledge',
    mcqTagHint: 'organizations',
  },
  {
    slug: 'saarc-regional-cooperation',
    title: 'SAARC and Regional Cooperation in South Asia',
    shortTitle: 'SAARC Cooperation',
    contentId: 'saarc-regional-cooperation',
    subjectSlugs: ['general-knowledge', 'current-affairs', 'pakistan-affairs'],
    syllabusHints: [
      'saarc',
      'sapta',
      'safta',
      'regional cooperation',
      'south asia',
    ],
    mcqSubjectSlug: 'general-knowledge',
    mcqTagHint: 'organizations',
  },

  // ── Islamic Studies ─────────────────────────────────────────────────
  {
    slug: 'pillars-of-islam',
    title: 'Five Pillars of Islam',
    shortTitle: 'Five Pillars',
    contentId: 'pillars-of-islam',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: ['pillars', 'salah', 'zakat', 'hajj', 'sawm', 'ibadat', 'worship'],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'ibadat',
  },
  {
    slug: 'hajj-umrah-fiqh-basics',
    title: 'Hajj and Umrah: Fiqh Basics',
    shortTitle: 'Hajj and Umrah',
    contentId: 'hajj-umrah-fiqh-basics',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'hajj',
      'umrah',
      'ihram',
      'arafah',
      'ibadat',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'ibadat',
  },
  {
    slug: 'ramadan-fasting-rules',
    title: 'Ramadan Fasting Rules (Sawm)',
    shortTitle: 'Ramadan Fasting',
    contentId: 'ramadan-fasting-rules',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'sawm',
      'ramadan',
      'fasting',
      'qada',
      'fidya',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'ibadat',
  },
  {
    slug: 'articles-of-faith-islam',
    title: 'Articles of Faith (Imaniyat)',
    shortTitle: 'Articles of Faith',
    contentId: 'articles-of-faith-islam',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'articles of faith',
      'imaniyat',
      'iman',
      'tawhid',
      'risalat',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'iman',
  },
  {
    slug: 'sources-of-islamic-law',
    title: 'Sources of Islamic Law (Usul)',
    shortTitle: 'Sources of Islamic Law',
    contentId: 'sources-of-islamic-law',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: ['sources of islamic law', 'usul', 'ijma', 'qiyas', 'fiqh', 'madhab'],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'fiqh',
  },
  {
    slug: 'quran-revelation-compilation',
    title: 'Revelation and Compilation of the Quran',
    shortTitle: 'Quran Compilation',
    contentId: 'quran-revelation-compilation',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: ['quran', 'revelation', 'compilation', 'uthman', 'abu bakr', 'makki', 'madani'],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'quran',
  },
  {
    slug: 'seerah-high-yield',
    title: 'Seerah High-Yield Facts (Prophet Muhammad PBUH)',
    shortTitle: 'Seerah Facts',
    contentId: 'seerah-high-yield',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: ['seerah', 'prophet', 'hijra', 'badr', 'uhud', 'makkah'],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'seerah',
  },
  {
    slug: 'life-of-prophet-makkah-period',
    title: 'Seerah Makkah Period',
    shortTitle: 'Seerah Makkah Period',
    contentId: 'life-of-prophet-makkah-period',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'seerah',
      'makkah period',
      'prophet',
      'hijra',
      'early islam',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'seerah',
  },
  {
    slug: 'life-of-prophet-madinah-period',
    title: 'Seerah Madinah Period',
    shortTitle: 'Seerah Madinah Period',
    contentId: 'life-of-prophet-madinah-period',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'seerah',
      'madinah period',
      'prophet',
      'badr',
      'uhud',
      'khandaq',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'seerah',
  },
  {
    slug: 'hadith-sciences-basics',
    title: 'Hadith Sciences Basics',
    shortTitle: 'Hadith Sciences',
    contentId: 'hadith-sciences-basics',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: ['hadith', 'bukhari', 'muslim', 'sihah', 'isnad'],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'hadith',
  },
  {
    slug: 'human-rights-in-islam',
    title: 'Human Rights in Islam',
    shortTitle: 'Human Rights in Islam',
    contentId: 'human-rights-in-islam',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'human rights in islam',
      'maqasid',
      'shariah',
      'islamic ethics',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'ethics',
  },
  {
    slug: 'status-of-women-in-islam',
    title: 'Status of Women in Islam',
    shortTitle: 'Women in Islam',
    contentId: 'status-of-women-in-islam',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'status of women',
      'women in islam',
      'mahr',
      'inheritance',
      'islamic social system',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'social-system',
  },
  {
    slug: 'islamic-civilization-contributions',
    title: 'Contributions of Islamic Civilization',
    shortTitle: 'Islamic Civilization',
    contentId: 'islamic-civilization-contributions',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'islamic civilization',
      'muslim contribution',
      'science',
      'knowledge',
      'golden age',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'civilization',
  },
  {
    slug: 'comparative-religions-basics',
    title: 'Comparative Religions Basics (CSS Islamiat)',
    shortTitle: 'Comparative Religions',
    contentId: 'comparative-religions-basics',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'comparative religions',
      'judaism',
      'christianity',
      'hinduism',
      'buddhism',
      'islamiat',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'comparative-religions',
  },
  {
    slug: 'zakat-system-social-welfare',
    title: 'Zakat System and Social Welfare',
    shortTitle: 'Zakat and Welfare',
    contentId: 'zakat-system-social-welfare',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'zakat',
      'nisab',
      'islamic economics',
      'social welfare',
      'ibadaat',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'zakat',
  },
  {
    slug: 'islamic-economic-system',
    title: 'Islamic Economic System',
    shortTitle: 'Islamic Economics',
    contentId: 'islamic-economic-system',
    subjectSlugs: ['islamic-studies'],
    syllabusHints: [
      'islamic economic system',
      'riba',
      'interest',
      'risk sharing',
      'zakat',
      'islamic finance',
    ],
    mcqSubjectSlug: 'islamic-studies',
    mcqTagHint: 'islamic-economics',
  },

  // ── English ─────────────────────────────────────────────────────────
  {
    slug: 'english-essay-css',
    title: 'CSS English Essay (Structure and Method)',
    shortTitle: 'English Essay Method',
    contentId: 'english-essay-css',
    subjectSlugs: ['english-essay', 'english'],
    syllabusHints: ['essay', 'english essay', 'outline', 'thesis'],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'essay',
  },
  {
    slug: 'precis-composition-css',
    title: 'Precis and Composition (CSS Method)',
    shortTitle: 'Precis Method',
    contentId: 'precis-composition-css',
    subjectSlugs: ['english-precis', 'english'],
    syllabusHints: ['precis', 'précis', 'composition', 'comprehension'],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'precis',
  },
  {
    slug: 'english-grammar-high-yield',
    title: 'English Grammar High-Yield for One-Paper Exams',
    shortTitle: 'English Grammar',
    contentId: 'english-grammar-high-yield',
    subjectSlugs: ['english'],
    syllabusHints: ['grammar', 'tenses', 'articles', 'prepositions', 'subject-verb'],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'grammar',
  },
  {
    slug: 'english-vocabulary-high-yield',
    title: 'English Vocabulary High-Yield (Synonyms Antonyms)',
    shortTitle: 'English Vocabulary',
    contentId: 'english-vocabulary-high-yield',
    subjectSlugs: ['english'],
    syllabusHints: [
      'vocabulary',
      'synonyms',
      'antonyms',
      'one-word substitution',
    ],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'vocabulary',
  },
  {
    slug: 'sentence-correction-method',
    title: 'Sentence Correction Method',
    shortTitle: 'Sentence Correction',
    contentId: 'sentence-correction-method',
    subjectSlugs: ['english'],
    syllabusHints: [
      'sentence correction',
      'grammar method',
      'error spotting',
      'english',
    ],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'grammar',
  },
  {
    slug: 'english-idioms-one-paper',
    title: 'English Idioms for One-Paper Exams',
    shortTitle: 'English Idioms',
    contentId: 'english-idioms-one-paper',
    subjectSlugs: ['english'],
    syllabusHints: [
      'idioms',
      'phrases',
      'vocabulary',
      'one-paper',
    ],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'idioms',
  },
  {
    slug: 'english-punctuation-capitalization',
    title: 'English Punctuation and Capitalization',
    shortTitle: 'Punctuation and Capitals',
    contentId: 'english-punctuation-capitalization',
    subjectSlugs: ['english'],
    syllabusHints: [
      'punctuation',
      'capitalization',
      'apostrophe',
      'comma',
      'one-paper english',
    ],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'grammar',
  },
  {
    slug: 'essay-outlining-workshop',
    title: 'Essay Outlining Workshop (CSS)',
    shortTitle: 'Essay Outlining',
    contentId: 'essay-outlining-workshop',
    subjectSlugs: ['english-essay', 'english'],
    syllabusHints: [
      'essay outline',
      'thesis',
      'counterargument',
      'english essay',
      'argumentation',
    ],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'essay',
  },
  {
    slug: 'comprehension-passage-method',
    title: 'Comprehension Passage Method (CSS/PMS)',
    shortTitle: 'Comprehension Method',
    contentId: 'comprehension-passage-method',
    subjectSlugs: ['english-precis', 'english'],
    syllabusHints: [
      'comprehension',
      'reading',
      'main idea',
      'inference',
      'vocabulary in context',
    ],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'comprehension',
  },
  {
    slug: 'translation-urdu-english-method',
    title: 'Urdu-English Translation Method (CSS)',
    shortTitle: 'Translation Method',
    contentId: 'translation-urdu-english-method',
    subjectSlugs: ['english-precis', 'english'],
    syllabusHints: [
      'translation',
      'urdu to english',
      'english to urdu',
      'idiom translation',
      'precis composition',
    ],
    mcqSubjectSlug: 'english',
    mcqTagHint: 'translation',
  },

  // ── GK / Science / Math / Computer / Geography ──────────────────────
  {
    slug: 'un-international-organizations',
    title: 'UN and Major International Organizations',
    shortTitle: 'UN and Organizations',
    contentId: 'un-international-organizations',
    subjectSlugs: ['general-knowledge', 'current-affairs'],
    syllabusHints: ['united nations', 'imf', 'world bank', 'oic', 'saarc', 'wto', 'sco'],
    mcqSubjectSlug: 'general-knowledge',
    mcqTagHint: 'organizations',
  },
  {
    slug: 'un-security-council-peacekeeping',
    title: 'UN Security Council and Peacekeeping',
    shortTitle: 'UNSC and Peacekeeping',
    contentId: 'un-security-council-peacekeeping',
    subjectSlugs: ['general-knowledge', 'current-affairs'],
    syllabusHints: [
      'security council',
      'unsc',
      'veto',
      'peacekeeping',
      'united nations',
    ],
    mcqSubjectSlug: 'general-knowledge',
    mcqTagHint: 'organizations',
  },
  {
    slug: 'world-organizations-imf-wb-wto',
    title: 'IMF, World Bank and WTO (Bretton Woods to Trade Rounds)',
    shortTitle: 'IMF, World Bank, WTO',
    contentId: 'world-organizations-imf-wb-wto',
    subjectSlugs: ['general-knowledge', 'current-affairs'],
    syllabusHints: [
      'bretton woods',
      'imf',
      'world bank',
      'wto',
      'gatt',
      'uruguay round',
      'doha',
    ],
    mcqSubjectSlug: 'general-knowledge',
    mcqTagHint: 'organizations',
  },
  {
    slug: 'world-physical-geography-basics',
    title: 'World Physical Geography Basics',
    shortTitle: 'World Physical Geography',
    contentId: 'world-physical-geography-basics',
    subjectSlugs: ['geography', 'general-knowledge'],
    syllabusHints: [
      'world geography',
      'physical geography',
      'peaks',
      'rivers',
      'deserts',
      'oceans',
    ],
    mcqSubjectSlug: 'geography',
    mcqTagHint: 'physical-geography',
  },
  {
    slug: 'computer-networking-basics',
    title: 'Computer Networking Basics (OSI and TCP/IP)',
    shortTitle: 'OSI and TCP/IP',
    contentId: 'computer-networking-basics',
    subjectSlugs: ['computer', 'basic-computer', 'computer-science'],
    syllabusHints: ['osi', 'tcp', 'networking', 'ports', 'ip'],
    mcqSubjectSlug: 'computer',
    mcqTagHint: 'networking',
  },
  {
    slug: 'computer-hardware-basics',
    title: 'Computer Hardware Basics (CPU, RAM, Storage, I/O)',
    shortTitle: 'Computer Hardware',
    contentId: 'computer-hardware-basics',
    subjectSlugs: ['computer', 'basic-computer', 'computer-science'],
    syllabusHints: [
      'cpu',
      'ram',
      'hardware',
      'storage',
      'input output',
      'basic computer',
    ],
    mcqSubjectSlug: 'computer',
    mcqTagHint: 'hardware',
  },
  {
    slug: 'boolean-logic-number-systems',
    title: 'Boolean Logic and Number Systems',
    shortTitle: 'Boolean and Number Systems',
    contentId: 'boolean-logic-number-systems',
    subjectSlugs: ['computer', 'basic-computer', 'computer-science'],
    syllabusHints: [
      'boolean',
      'binary',
      'hexadecimal',
      'and or not',
      'number systems',
    ],
    mcqSubjectSlug: 'computer',
    mcqTagHint: 'fundamentals',
  },
  {
    slug: 'vitamins-hormones-basics',
    title: 'Vitamins, Hormones and Deficiency Diseases',
    shortTitle: 'Vitamins and Hormones',
    contentId: 'vitamins-hormones-basics',
    subjectSlugs: ['everyday-science'],
    syllabusHints: ['vitamin', 'hormone', 'deficiency', 'insulin', 'human body'],
    mcqSubjectSlug: 'everyday-science',
    mcqTagHint: 'biology',
  },
  {
    slug: 'biology-human-systems',
    title: 'Human Body Systems (Digestive, Circulatory, Nervous, Respiratory)',
    shortTitle: 'Human Body Systems',
    contentId: 'biology-human-systems',
    subjectSlugs: ['everyday-science'],
    syllabusHints: [
      'human body',
      'digestive',
      'circulatory',
      'nervous',
      'respiratory',
      'biology',
    ],
    mcqSubjectSlug: 'everyday-science',
    mcqTagHint: 'biology',
  },
  {
    slug: 'everyday-science-physics-basics',
    title: 'Everyday Science Physics Basics',
    shortTitle: 'Physics Basics',
    contentId: 'everyday-science-physics-basics',
    subjectSlugs: ['everyday-science'],
    syllabusHints: [
      'physics',
      'si units',
      'newton',
      'optics',
      'everyday science',
    ],
    mcqSubjectSlug: 'everyday-science',
    mcqTagHint: 'physics',
  },
  {
    slug: 'everyday-science-chemistry-basics',
    title: 'Everyday Science Chemistry Basics',
    shortTitle: 'Chemistry Basics',
    contentId: 'everyday-science-chemistry-basics',
    subjectSlugs: ['everyday-science'],
    syllabusHints: [
      'chemistry',
      'acids',
      'bases',
      'elements',
      'everyday science',
    ],
    mcqSubjectSlug: 'everyday-science',
    mcqTagHint: 'chemistry',
  },
  {
    slug: 'percentages-ratios-profit-loss',
    title: 'Percentages, Ratios and Profit Loss',
    shortTitle: 'Percentages and Profit Loss',
    contentId: 'percentages-ratios-profit-loss',
    subjectSlugs: ['mathematics'],
    syllabusHints: ['percentage', 'ratio', 'profit', 'loss', 'arithmetic'],
    mcqSubjectSlug: 'mathematics',
    mcqTagHint: 'arithmetic',
  },
  {
    slug: 'percentages-applications-exam',
    title: 'Percentages: Advanced Applications for Exams',
    shortTitle: 'Percentage Applications',
    contentId: 'percentages-applications-exam',
    subjectSlugs: ['mathematics'],
    syllabusHints: [
      'successive percentage',
      'population growth',
      'reverse percentage',
      'compound growth',
      'arithmetic',
    ],
    mcqSubjectSlug: 'mathematics',
    mcqTagHint: 'arithmetic',
  },
  {
    slug: 'ratio-proportion-averages',
    title: 'Ratio, Proportion and Averages',
    shortTitle: 'Ratio and Averages',
    contentId: 'ratio-proportion-averages',
    subjectSlugs: ['mathematics'],
    syllabusHints: [
      'ratio',
      'proportion',
      'average',
      'mean',
      'weighted average',
      'general math',
    ],
    mcqSubjectSlug: 'mathematics',
    mcqTagHint: 'arithmetic',
  },
  {
    slug: 'set-theory-basics-math',
    title: 'Set Theory Basics (One-Paper Math)',
    shortTitle: 'Set Theory Basics',
    contentId: 'set-theory-basics-math',
    subjectSlugs: ['mathematics'],
    syllabusHints: [
      'set theory',
      'venn',
      'union',
      'intersection',
      'general math',
    ],
    mcqSubjectSlug: 'mathematics',
    mcqTagHint: 'sets',
  },
  {
    slug: 'probability-basics-exam',
    title: 'Probability Basics for One-Paper Exams',
    shortTitle: 'Probability Basics',
    contentId: 'probability-basics-exam',
    subjectSlugs: ['mathematics'],
    syllabusHints: [
      'probability',
      'complement',
      'mutually exclusive',
      'independent events',
      'one-paper math',
    ],
    mcqSubjectSlug: 'mathematics',
    mcqTagHint: 'probability',
  },

  // ── Ethics / Civics / Governance ────────────────────────────────────
  {
    slug: 'ethics-theories-basics',
    title: 'Ethical Theories for Civil Service Exams',
    shortTitle: 'Ethical Theories',
    contentId: 'ethics-theories-basics',
    subjectSlugs: ['ethics-civics', 'general-knowledge'],
    syllabusHints: ['ethics', 'utilitarianism', 'kant', 'rawls', 'virtue'],
    mcqSubjectSlug: 'ethics-civics',
    mcqTagHint: 'ethics',
  },
  {
    slug: 'good-governance-undp',
    title: 'Good Governance Principles',
    shortTitle: 'Good Governance',
    contentId: 'good-governance-undp',
    subjectSlugs: ['ethics-civics', 'pakistan-affairs', 'general-knowledge'],
    syllabusHints: ['good governance', 'transparency', 'accountability', 'rule of law', 'undp'],
    mcqSubjectSlug: 'ethics-civics',
    mcqTagHint: 'governance',
  },
  {
    slug: 'public-service-values',
    title: 'Public Service Values and Integrity',
    shortTitle: 'Public Service Values',
    contentId: 'public-service-values',
    subjectSlugs: ['ethics-civics', 'pakistan-affairs'],
    syllabusHints: [
      'public service',
      'integrity',
      'civil service ethics',
      'public administration',
    ],
    mcqSubjectSlug: 'ethics-civics',
    mcqTagHint: 'ethics',
  },
  {
    slug: 'separation-of-powers-pakistan',
    title: 'Separation of Powers in Pakistan',
    shortTitle: 'Separation of Powers',
    contentId: 'separation-of-powers-pakistan',
    subjectSlugs: ['ethics-civics', 'pakistan-affairs'],
    syllabusHints: [
      'separation of powers',
      'legislature',
      'executive',
      'judiciary',
      '1973 constitution',
    ],
    mcqSubjectSlug: 'ethics-civics',
    mcqTagHint: 'governance',
  },
  {
    slug: 'sdgs-pakistan',
    title: 'Sustainable Development Goals (SDGs)',
    shortTitle: 'SDGs',
    contentId: 'sdgs-pakistan',
    subjectSlugs: ['ethics-civics', 'current-affairs', 'general-knowledge'],
    syllabusHints: ['sdg', 'sustainable development', '2030', 'poverty', 'gender'],
    mcqSubjectSlug: 'current-affairs',
    mcqTagHint: 'sdgs',
  },
  {
    slug: 'human-rights-udhr',
    title: 'Human Rights Framework (UDHR and Core Treaties)',
    shortTitle: 'Human Rights',
    contentId: 'human-rights-udhr',
    subjectSlugs: ['ethics-civics', 'pakistan-affairs', 'general-knowledge'],
    syllabusHints: [
      'human rights',
      'udhr',
      'iccpr',
      'cedaw',
      'fundamental rights',
      'articles 8-28',
    ],
    mcqSubjectSlug: 'ethics-civics',
    mcqTagHint: 'human-rights',
  },
]

const KITS: Record<string, NoteKitData> = {
  'objectives-resolution-article-2a': OBJECTIVES_RESOLUTION_KIT,
  'constitution-1973': CONSTITUTION_1973_KIT,
  'constitution-fundamental-rights': CONSTITUTION_FUNDAMENTAL_RIGHTS_KIT,
  'constitution-principles-policy': CONSTITUTION_PRINCIPLES_POLICY_KIT,
  'islamic-provisions-1973': ISLAMIC_PROVISIONS_1973_KIT,
  'eighteenth-amendment': EIGHTEENTH_AMENDMENT_KIT,
  'lahore-resolution-1940': LAHORE_RESOLUTION_KIT,
  'ideology-of-pakistan': IDEOLOGY_OF_PAKISTAN_KIT,
  'two-nation-theory': TWO_NATION_THEORY_KIT,
  'allama-iqbal-allahabad': ALLAMA_IQBAL_ALLAHABAD_KIT,
  'quaid-e-azam-political-leadership': QUAID_E_AZAM_POLITICAL_LEADERSHIP_KIT,
  'pakistan-movement-1857-1947': PAKISTAN_MOVEMENT_1857_1947_KIT,
  'constitutional-development-pakistan': CONSTITUTIONAL_DEVELOPMENT_PAKISTAN_KIT,
  'federation-provincial-autonomy': FEDERATION_PROVINCIAL_AUTONOMY_KIT,
  'civil-military-relations': CIVIL_MILITARY_RELATIONS_KIT,
  'foreign-policy-post-911': FOREIGN_POLICY_POST_911_KIT,
  'pakistan-foreign-policy-principles': PAKISTAN_FOREIGN_POLICY_PRINCIPLES_KIT,
  'pakistan-india-relations': PAKISTAN_INDIA_RELATIONS_KIT,
  'kashmir-dispute-basics': KASHMIR_DISPUTE_BASICS_KIT,
  'pakistan-usa-relations': PAKISTAN_USA_RELATIONS_KIT,
  'pakistan-china-relations': PAKISTAN_CHINA_RELATIONS_KIT,
  'pakistan-iran-relations': PAKISTAN_IRAN_RELATIONS_KIT,
  'pakistan-saudi-relations': PAKISTAN_SAUDI_RELATIONS_KIT,
  'political-evolution-1971': POLITICAL_EVOLUTION_1971_KIT,
  'democracy-evolution-pakistan': DEMOCRACY_EVOLUTION_PAKISTAN_KIT,
  'land-people-pakistan': LAND_PEOPLE_PAKISTAN_KIT,
  'physical-geography-pakistan': PHYSICAL_GEOGRAPHY_PAKISTAN_KIT,
  'indus-river-system': INDUS_RIVER_SYSTEM_KIT,
  'indus-waters-treaty-deep': INDUS_WATERS_TREATY_DEEP_KIT,
  'population-demographics-pakistan': POPULATION_DEMOGRAPHICS_PAKISTAN_KIT,
  'pakistan-nuclear-program': PAKISTAN_NUCLEAR_PROGRAM_KIT,
  'education-system-pakistan': EDUCATION_SYSTEM_PAKISTAN_KIT,
  'language-policy-pakistan': LANGUAGE_POLICY_PAKISTAN_KIT,
  'cultural-heritage-pakistan': CULTURAL_HERITAGE_PAKISTAN_KIT,
  'health-system-pakistan': HEALTH_SYSTEM_PAKISTAN_KIT,
  'urbanization-housing-pakistan': URBANIZATION_HOUSING_PAKISTAN_KIT,
  'karachi-urban-governance': KARACHI_URBAN_GOVERNANCE_KIT,
  'disaster-management-pakistan': DISASTER_MANAGEMENT_PAKISTAN_KIT,
  'social-problems-pakistan': SOCIAL_PROBLEMS_PAKISTAN_KIT,
  'nfc-award-fiscal-federalism': NFC_AWARD_FISCAL_FEDERALISM_KIT,
  'local-government-pakistan': LOCAL_GOVERNMENT_PAKISTAN_KIT,
  'media-and-civil-society-pakistan': MEDIA_CIVIL_SOCIETY_PAKISTAN_KIT,
  'women-empowerment-pakistan': WOMEN_EMPOWERMENT_PAKISTAN_KIT,
  'energy-crisis-pakistan': ENERGY_CRISIS_PAKISTAN_KIT,
  'water-crisis-pakistan': WATER_CRISIS_PAKISTAN_KIT,
  'bureaucracy-reform-pakistan': BUREAUCRACY_REFORM_PAKISTAN_KIT,
  'judiciary-pakistan-basics': JUDICIARY_PAKISTAN_BASICS_KIT,
  'agriculture-pakistan': AGRICULTURE_PAKISTAN_KIT,
  'industry-and-trade-pakistan': INDUSTRY_TRADE_PAKISTAN_KIT,
  'terrorism-extremism-pakistan': TERRORISM_EXTREMISM_PAKISTAN_KIT,
  'balochistan-issues-exam': BALOCHISTAN_ISSUES_EXAM_KIT,
  'afghanistan-pakistan-relations': AFGHANISTAN_PAKISTAN_RELATIONS_KIT,
  'muslim-world-pakistan': MUSLIM_WORLD_PAKISTAN_KIT,
  'environmental-pollution-pakistan': ENVIRONMENTAL_POLLUTION_PAKISTAN_KIT,
  'cpec-and-regional-connectivity': CPEC_REGIONAL_CONNECTIVITY_KIT,
  'cpec-gwadar-deep-dive': CPEC_GWADAR_DEEP_DIVE_KIT,
  'pakistan-economy-imf-sbp': PAKISTAN_ECONOMY_IMF_SBP_KIT,
  'budget-fiscal-policy-pakistan': BUDGET_FISCAL_POLICY_PAKISTAN_KIT,
  'inflation-monetary-policy': INFLATION_MONETARY_POLICY_KIT,
  'climate-floods-smog-pakistan': CLIMATE_FLOODS_SMOG_PAKISTAN_KIT,
  'climate-change-pakistan-policy': CLIMATE_CHANGE_PAKISTAN_POLICY_KIT,
  'oic-saarc-sco': OIC_SAARC_SCO_KIT,
  'saarc-regional-cooperation': SAARC_REGIONAL_COOPERATION_KIT,
  'pillars-of-islam': PILLARS_OF_ISLAM_KIT,
  'hajj-umrah-fiqh-basics': HAJJ_UMRAH_FIQH_BASICS_KIT,
  'ramadan-fasting-rules': RAMADAN_FASTING_RULES_KIT,
  'articles-of-faith-islam': ARTICLES_OF_FAITH_ISLAM_KIT,
  'sources-of-islamic-law': SOURCES_OF_ISLAMIC_LAW_KIT,
  'quran-revelation-compilation': QURAN_REVELATION_COMPILATION_KIT,
  'seerah-high-yield': SEERAH_HIGH_YIELD_KIT,
  'life-of-prophet-makkah-period': LIFE_OF_PROPHET_MAKKAH_PERIOD_KIT,
  'life-of-prophet-madinah-period': LIFE_OF_PROPHET_MADINAH_PERIOD_KIT,
  'hadith-sciences-basics': HADITH_SCIENCES_BASICS_KIT,
  'human-rights-in-islam': HUMAN_RIGHTS_IN_ISLAM_KIT,
  'status-of-women-in-islam': STATUS_OF_WOMEN_IN_ISLAM_KIT,
  'islamic-civilization-contributions': ISLAMIC_CIVILIZATION_CONTRIBUTIONS_KIT,
  'comparative-religions-basics': COMPARATIVE_RELIGIONS_BASICS_KIT,
  'zakat-system-social-welfare': ZAKAT_SYSTEM_SOCIAL_WELFARE_KIT,
  'islamic-economic-system': ISLAMIC_ECONOMIC_SYSTEM_KIT,
  'english-essay-css': ENGLISH_ESSAY_CSS_KIT,
  'precis-composition-css': PRECIS_COMPOSITION_CSS_KIT,
  'english-grammar-high-yield': ENGLISH_GRAMMAR_HIGH_YIELD_KIT,
  'english-vocabulary-high-yield': ENGLISH_VOCABULARY_HIGH_YIELD_KIT,
  'sentence-correction-method': SENTENCE_CORRECTION_METHOD_KIT,
  'english-idioms-one-paper': ENGLISH_IDIOMS_ONE_PAPER_KIT,
  'english-punctuation-capitalization': ENGLISH_PUNCTUATION_CAPITALIZATION_KIT,
  'essay-outlining-workshop': ESSAY_OUTLINING_WORKSHOP_KIT,
  'comprehension-passage-method': COMPREHENSION_PASSAGE_METHOD_KIT,
  'translation-urdu-english-method': TRANSLATION_URDU_ENGLISH_METHOD_KIT,
  'un-international-organizations': UN_INTERNATIONAL_ORGANIZATIONS_KIT,
  'un-security-council-peacekeeping': UN_SECURITY_COUNCIL_PEACEKEEPING_KIT,
  'world-organizations-imf-wb-wto': WORLD_ORGANIZATIONS_IMF_WB_WTO_KIT,
  'world-physical-geography-basics': WORLD_PHYSICAL_GEOGRAPHY_BASICS_KIT,
  'computer-networking-basics': COMPUTER_NETWORKING_BASICS_KIT,
  'computer-hardware-basics': COMPUTER_HARDWARE_BASICS_KIT,
  'boolean-logic-number-systems': BOOLEAN_LOGIC_NUMBER_SYSTEMS_KIT,
  'vitamins-hormones-basics': VITAMINS_HORMONES_BASICS_KIT,
  'biology-human-systems': BIOLOGY_HUMAN_SYSTEMS_KIT,
  'everyday-science-physics-basics': EVERYDAY_SCIENCE_PHYSICS_BASICS_KIT,
  'everyday-science-chemistry-basics': EVERYDAY_SCIENCE_CHEMISTRY_BASICS_KIT,
  'percentages-ratios-profit-loss': PERCENTAGES_RATIOS_PROFIT_LOSS_KIT,
  'percentages-applications-exam': PERCENTAGES_APPLICATIONS_EXAM_KIT,
  'ratio-proportion-averages': RATIO_PROPORTION_AVERAGES_KIT,
  'set-theory-basics-math': SET_THEORY_BASICS_MATH_KIT,
  'probability-basics-exam': PROBABILITY_BASICS_EXAM_KIT,
  'ethics-theories-basics': ETHICS_THEORIES_BASICS_KIT,
  'good-governance-undp': GOOD_GOVERNANCE_UNDP_KIT,
  'public-service-values': PUBLIC_SERVICE_VALUES_KIT,
  'separation-of-powers-pakistan': SEPARATION_OF_POWERS_PAKISTAN_KIT,
  'sdgs-pakistan': SDGS_PAKISTAN_KIT,
  'human-rights-udhr': HUMAN_RIGHTS_UDHR_KIT,
}

export function listRegisteredTopics(): NoteTopicMeta[] {
  return TOPICS
}

export function getRegisteredTopic(slug: string): NoteTopicMeta | null {
  return TOPICS.find((t) => t.slug === slug) ?? null
}

export function getRegisteredTopicForSubject(subjectSlug: string): NoteTopicMeta[] {
  return TOPICS.filter((t) => t.subjectSlugs.includes(subjectSlug))
}

export function getNoteKit(contentId: string): NoteKitData | null {
  return KITS[contentId] ?? null
}

export function resolveTopicKit(
  topicSlug: string
): { meta: NoteTopicMeta; kit: NoteKitData } | null {
  const meta = getRegisteredTopic(topicSlug)
  if (!meta) return null
  const kit = getNoteKit(meta.contentId)
  if (!kit) return null
  return { meta, kit }
}
