/**
 * Seed ISSB MCQ banks with student-first quality: every row has a clear explanation.
 * Run: npx tsx scripts/seed-issb-mcqs.ts
 */
import { createClient } from '@supabase/supabase-js'

type Row = {
  question: string
  option_a: string
  option_b: string
  option_c: string
  option_d: string
  correct_answer: 'A' | 'B' | 'C' | 'D'
  explanation: string
  topic: string
  difficulty: 'easy' | 'medium' | 'hard'
  type: 'practice' | 'most_important' | 'most_repeated'
}

const ISSB_ENGLISH: Row[] = [
  {
    question: 'Choose the word most similar in meaning to "CANDID":',
    option_a: 'Deceptive',
    option_b: 'Frank',
    option_c: 'Hostile',
    option_d: 'Timid',
    correct_answer: 'B',
    explanation: 'Candid means honest and straightforward. Frank is the closest synonym. Deceptive is the opposite; hostile and timid describe attitude, not honesty.',
    topic: 'synonyms',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'Fill in the blank: "The officer gave a ______ speech that inspired the entire platoon."',
    option_a: 'tedious',
    option_b: 'rousing',
    option_c: 'ambiguous',
    option_d: 'reluctant',
    correct_answer: 'B',
    explanation: 'Rousing means inspiring and energizing — it fits a speech that motivated a platoon. Tedious means boring; ambiguous means unclear; reluctant means unwilling.',
    topic: 'fill_in_blanks',
    difficulty: 'easy',
    type: 'most_important',
  },
  {
    question: 'Identify the grammatically correct sentence:',
    option_a: 'Neither the captain nor the lieutenants was present.',
    option_b: 'Neither the captain nor the lieutenants were present.',
    option_c: 'Neither the captain nor the lieutenants is present.',
    option_d: 'Neither the captain nor the lieutenants has present.',
    correct_answer: 'B',
    explanation: 'With "neither...nor", the verb agrees with the nearer subject. "Lieutenants" is plural, so "were" is correct. Option A wrongly uses singular "was".',
    topic: 'sentence_correction',
    difficulty: 'medium',
    type: 'most_repeated',
  },
  {
    question: 'Antonym of "ABSTAIN":',
    option_a: 'Refrain',
    option_b: 'Participate',
    option_c: 'Withdraw',
    option_d: 'Avoid',
    correct_answer: 'B',
    explanation: 'Abstain means to hold back or not take part. Participate is the direct opposite. Refrain, withdraw, and avoid are synonyms of abstain.',
    topic: 'antonyms',
    difficulty: 'easy',
    type: 'practice',
  },
  {
    question: 'One word for "A person who hates mankind":',
    option_a: 'Philanthropist',
    option_b: 'Misanthrope',
    option_c: 'Optimist',
    option_d: 'Altruist',
    correct_answer: 'B',
    explanation: 'Misanthrope (Greek: misein = hate, anthropos = man) means a hater of humankind. Philanthropist and altruist love/help others; optimist expects the best.',
    topic: 'one_word_substitution',
    difficulty: 'medium',
    type: 'most_important',
  },
  {
    question: 'Choose the correct preposition: "He is adept ______ handling difficult situations."',
    option_a: 'in',
    option_b: 'at',
    option_c: 'on',
    option_d: 'with',
    correct_answer: 'B',
    explanation: 'The fixed collocation is "adept at" + gerund/noun. "Adept in" is sometimes heard but "adept at" is standard in ISSB/ competitive English papers.',
    topic: 'prepositions',
    difficulty: 'medium',
    type: 'most_repeated',
  },
  {
    question: '"Every cloud has a silver lining" means:',
    option_a: 'Weather improves after rain',
    option_b: 'Every bad situation has a hopeful aspect',
    option_c: 'Wealth is hidden in difficulty',
    option_d: 'Clouds contain metal',
    correct_answer: 'B',
    explanation: 'This proverb means optimism — even in hardship, something good can emerge. It tests idiomatic understanding common in ISSB English sections.',
    topic: 'idioms',
    difficulty: 'easy',
    type: 'practice',
  },
  {
    question: 'The synonym of "METICULOUS" is:',
    option_a: 'Careless',
    option_b: 'Hasty',
    option_c: 'Thorough',
    option_d: 'Lazy',
    correct_answer: 'C',
    explanation: 'Meticulous means showing great attention to detail — thorough fits best. Careless, hasty, and lazy are antonyms.',
    topic: 'synonyms',
    difficulty: 'medium',
    type: 'most_repeated',
  },
  {
    question: 'Correct spelling:',
    option_a: 'Accomodation',
    option_b: 'Accommodation',
    option_c: 'Acommodation',
    option_d: 'Acomodation',
    correct_answer: 'B',
    explanation: 'Accommodation has double "c" and double "m". Spelling traps are common in ISSB English — learn high-frequency misspellings.',
    topic: 'spelling',
    difficulty: 'easy',
    type: 'practice',
  },
  {
    question: '"Brevity is the soul of wit" was stated by:',
    option_a: 'Milton',
    option_b: 'Shakespeare',
    option_c: 'Wordsworth',
    option_d: 'Keats',
    correct_answer: 'B',
    explanation: 'From Hamlet (Polonius). ISSB English often includes famous literary lines — link quotes to authors for quick marks.',
    topic: 'literature',
    difficulty: 'hard',
    type: 'most_important',
  },
]

const ISSB_MATHEMATICS: Row[] = [
  {
    question: 'If 30% of a number is 45, what is the number?',
    option_a: '120',
    option_b: '135',
    option_c: '150',
    option_d: '165',
    correct_answer: 'C',
    explanation: '30% of x = 45 → x = 45 ÷ 0.30 = 150. Shortcut: 10% = 15, so 30% = 45 confirms x = 150.',
    topic: 'percentages',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'What is the next number in the series: 2, 6, 12, 20, 30, ?',
    option_a: '40',
    option_b: '42',
    option_c: '44',
    option_d: '46',
    correct_answer: 'B',
    explanation: 'Differences: +4, +6, +8, +10 → next difference +12. 30 + 12 = 42. ISSB loves simple increasing-difference series.',
    topic: 'number_series',
    difficulty: 'medium',
    type: 'most_important',
  },
  {
    question: 'A train 150 m long passes a pole in 15 seconds. Its speed in km/h is:',
    option_a: '36',
    option_b: '40',
    option_c: '45',
    option_d: '54',
    correct_answer: 'A',
    explanation: 'Speed = 150 m / 15 s = 10 m/s. Convert: 10 × (18/5) = 36 km/h. Remember m/s to km/h: multiply by 18/5.',
    topic: 'speed_distance',
    difficulty: 'medium',
    type: 'most_repeated',
  },
  {
    question: 'The ratio of two numbers is 3:5. If their sum is 64, the larger number is:',
    option_a: '24',
    option_b: '35',
    option_c: '40',
    option_d: '45',
    correct_answer: 'C',
    explanation: 'Parts 3 + 5 = 8. One part = 64/8 = 8. Larger = 5 × 8 = 40. Always total the ratio parts first.',
    topic: 'ratios',
    difficulty: 'easy',
    type: 'practice',
  },
  {
    question: 'If x² − 9 = 0, then x equals:',
    option_a: '3 only',
    option_b: '−3 only',
    option_c: '3 or −3',
    option_d: '9',
    correct_answer: 'C',
    explanation: 'x² = 9 → x = ±3. Both roots matter — ISSB often traps students who pick only the positive root.',
    topic: 'algebra',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'Average of 5 numbers is 20. If one number is removed, average becomes 18. The removed number is:',
    option_a: '24',
    option_b: '26',
    option_c: '28',
    option_d: '30',
    correct_answer: 'C',
    explanation: 'Sum of 5 = 100. Sum of 4 = 72. Removed = 100 − 72 = 28. Use totals, not averages, when numbers are added/removed.',
    topic: 'averages',
    difficulty: 'medium',
    type: 'most_important',
  },
  {
    question: 'What is 0.625 as a fraction in lowest terms?',
    option_a: '5/8',
    option_b: '625/1000',
    option_c: '2/3',
    option_d: '3/5',
    correct_answer: 'A',
    explanation: '0.625 = 625/1000 = 5/8 (divide by 125). Learn common decimals: 0.125=1/8, 0.375=3/8, 0.625=5/8, 0.875=7/8.',
    topic: 'fractions',
    difficulty: 'medium',
    type: 'practice',
  },
  {
    question: 'A shopkeeper marks goods 25% above cost and gives 10% discount. Profit % is:',
    option_a: '12.5%',
    option_b: '15%',
    option_c: '17.5%',
    option_d: '22.5%',
    correct_answer: 'A',
    explanation: 'SP = 125% × 90% of CP = 1.125 × CP → 12.5% profit. Chain percentage: multiply factors, subtract 1, ×100.',
    topic: 'profit_loss',
    difficulty: 'hard',
    type: 'most_repeated',
  },
  {
    question: 'How many degrees in the sum of interior angles of a hexagon?',
    option_a: '540',
    option_b: '620',
    option_c: '720',
    option_d: '900',
    correct_answer: 'C',
    explanation: 'Formula: (n−2)×180°. Hexagon n=6 → 4×180 = 720°. ISSB geometry basics appear regularly.',
    topic: 'geometry',
    difficulty: 'medium',
    type: 'practice',
  },
  {
    question: 'If 12 workers finish a job in 8 days, how many days for 16 workers (same rate)?',
    option_a: '4',
    option_b: '5',
    option_c: '6',
    option_d: '7',
    correct_answer: 'C',
    explanation: 'Total work = 12×8 = 96 worker-days. 96/16 = 6 days. Inverse proportion: more workers → fewer days.',
    topic: 'work_time',
    difficulty: 'easy',
    type: 'most_important',
  },
]

const ISSB_GK: Row[] = [
  {
    question: 'Which planet is known as the Red Planet?',
    option_a: 'Venus',
    option_b: 'Mars',
    option_c: 'Jupiter',
    option_d: 'Saturn',
    correct_answer: 'B',
    explanation: 'Mars appears red due to iron oxide (rust) on its surface. Venus is the morning/evening star; Jupiter and Saturn are gas giants.',
    topic: 'science',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'The SI unit of electric current is:',
    option_a: 'Volt',
    option_b: 'Ohm',
    option_c: 'Ampere',
    option_d: 'Watt',
    correct_answer: 'C',
    explanation: 'Ampere (A) measures current. Volt = potential difference; Ohm = resistance; Watt = power. Know base SI units for ISSB science GK.',
    topic: 'physics_basics',
    difficulty: 'easy',
    type: 'practice',
  },
  {
    question: 'UN headquarters is located in:',
    option_a: 'Geneva',
    option_b: 'New York',
    option_c: 'Paris',
    option_d: 'The Hague',
    correct_answer: 'B',
    explanation: 'UN HQ is in New York City (USA). Geneva hosts many UN agencies; The Hague is ICJ/ICC; Paris is UNESCO HQ.',
    topic: 'international_organizations',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'Human body temperature in Celsius is normally about:',
    option_a: '35°C',
    option_b: '36°C',
    option_c: '37°C',
    option_d: '38°C',
    correct_answer: 'C',
    explanation: 'Normal body temperature ≈ 37°C (98.6°F). 38°C+ often indicates fever. Basic biology facts appear in ISSB GK.',
    topic: 'biology_basics',
    difficulty: 'easy',
    type: 'most_important',
  },
  {
    question: 'Which gas is most abundant in Earth\'s atmosphere?',
    option_a: 'Oxygen',
    option_b: 'Carbon dioxide',
    option_c: 'Nitrogen',
    option_d: 'Hydrogen',
    correct_answer: 'C',
    explanation: 'Nitrogen ≈ 78%, Oxygen ≈ 21%. Students often wrongly pick oxygen because we breathe it — nitrogen dominates by volume.',
    topic: 'science',
    difficulty: 'medium',
    type: 'most_repeated',
  },
  {
    question: 'The Nobel Peace Prize is awarded in:',
    option_a: 'Stockholm',
    option_b: 'Oslo',
    option_c: 'Copenhagen',
    option_d: 'Helsinki',
    correct_answer: 'B',
    explanation: 'Peace Prize ceremony is in Oslo, Norway. Other Nobel prizes are in Stockholm, Sweden — a classic competitive exam trap.',
    topic: 'awards',
    difficulty: 'medium',
    type: 'most_important',
  },
  {
    question: 'Deficiency of Vitamin D causes:',
    option_a: 'Scurvy',
    option_b: 'Rickets',
    option_c: 'Beriberi',
    option_d: 'Pellagra',
    correct_answer: 'B',
    explanation: 'Vitamin D deficiency → rickets (soft bones in children). Scurvy = Vitamin C; Beriberi = B1; Pellagra = B3.',
    topic: 'health',
    difficulty: 'medium',
    type: 'practice',
  },
  {
    question: 'Which ocean is the largest by area?',
    option_a: 'Atlantic',
    option_b: 'Indian',
    option_c: 'Pacific',
    option_d: 'Arctic',
    correct_answer: 'C',
    explanation: 'Pacific Ocean is the largest and deepest. It covers more area than all land combined — fundamental geography fact.',
    topic: 'geography',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'CPU stands for:',
    option_a: 'Central Processing Unit',
    option_b: 'Computer Personal Unit',
    option_c: 'Central Program Utility',
    option_d: 'Control Processing Unit',
    correct_answer: 'A',
    explanation: 'CPU = Central Processing Unit — the brain of a computer executing instructions. Basic IT literacy is tested at ISSB.',
    topic: 'computer_basics',
    difficulty: 'easy',
    type: 'practice',
  },
  {
    question: 'The hardest natural substance on Earth is:',
    option_a: 'Gold',
    option_b: 'Iron',
    option_c: 'Diamond',
    option_d: 'Platinum',
    correct_answer: 'C',
    explanation: 'Diamond ranks 10 on Mohs hardness scale. Used in cutting tools. Gold/platinum are precious metals, not hardest minerals.',
    topic: 'science',
    difficulty: 'easy',
    type: 'most_important',
  },
]

const ISSB_PAKISTAN: Row[] = [
  {
    question: 'Pakistan Resolution was passed on:',
    option_a: '23 March 1940',
    option_b: '14 August 1947',
    option_c: '26 March 1971',
    option_d: '16 December 1971',
    correct_answer: 'A',
    explanation: '23 March 1940 — Lahore Resolution demanded independent states for Muslims. 14 Aug 1947 = Independence; 1971 dates relate to Bangladesh.',
    topic: 'pakistan_history',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'First Governor-General of Pakistan was:',
    option_a: 'Liaquat Ali Khan',
    option_b: 'Quaid-e-Azam Muhammad Ali Jinnah',
    option_c: 'Khawaja Nazimuddin',
    option_d: 'Iskander Mirza',
    correct_answer: 'B',
    explanation: 'Jinnah served as Governor-General until his death in September 1948. Liaquat Ali Khan was the first Prime Minister.',
    topic: 'pakistan_history',
    difficulty: 'easy',
    type: 'most_important',
  },
  {
    question: 'The national language of Pakistan is:',
    option_a: 'Punjabi',
    option_b: 'Urdu',
    option_c: 'Sindhi',
    option_d: 'English',
    correct_answer: 'B',
    explanation: 'Article 251 of the Constitution declares Urdu the national language. English is official for government/business; provincial languages have regional status.',
    topic: 'constitution',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'K2, the second-highest peak in the world, is located in:',
    option_a: 'Nepal',
    option_b: 'Pakistan',
    option_c: 'India',
    option_d: 'China only',
    correct_answer: 'B',
    explanation: 'K2 (8,611 m) is in Gilgit-Baltistan, Pakistan, on the Pakistan-China border. Highest peak is Everest (Nepal/Tibet).',
    topic: 'geography',
    difficulty: 'easy',
    type: 'practice',
  },
  {
    question: 'Objectives Resolution was adopted in:',
    option_a: '1947',
    option_b: '1949',
    option_c: '1956',
    option_d: '1973',
    correct_answer: 'B',
    explanation: 'March 1949 — Objectives Resolution laid Islamic democratic principles guiding later constitutions. 1973 Constitution is the current one.',
    topic: 'constitution',
    difficulty: 'medium',
    type: 'most_important',
  },
  {
    question: 'Indus River enters Pakistan from:',
    option_a: 'Afghanistan',
    option_b: 'China (Tibet/GB)',
    option_c: 'Iran',
    option_d: 'India only',
    correct_answer: 'B',
    explanation: 'Indus originates in Tibet, flows through Gilgit-Baltistan into KPK and Punjab. It is Pakistan\'s lifeline — key for ISSB geography.',
    topic: 'geography',
    difficulty: 'medium',
    type: 'most_repeated',
  },
  {
    question: 'The length of Pakistan-China border is approximately:',
    option_a: '596 km',
    option_b: '909 km',
    option_c: '1200 km',
    option_d: '2400 km',
    correct_answer: 'A',
    explanation: 'Pak-China border ≈ 596 km along GB (Karakoram). Longer borders: Afghanistan ~2,640 km; India ~3,320 km.',
    topic: 'borders',
    difficulty: 'hard',
    type: 'practice',
  },
  {
    question: 'Which city is known as the "City of Saints"?',
    option_a: 'Lahore',
    option_b: 'Multan',
    option_c: 'Karachi',
    option_d: 'Peshawar',
    correct_answer: 'B',
    explanation: 'Multan — historic Sufi shrines (Bahauddin Zakariya, Shah Rukn-e-Alam). Lahore is "Heart of Pakistan"; Peshawar is frontier city.',
    topic: 'culture',
    difficulty: 'medium',
    type: 'most_repeated',
  },
  {
    question: 'Pakistan\'s first nuclear test was conducted in:',
    option_a: '1996',
    option_b: '1998',
    option_c: '2000',
    option_d: '1974',
    correct_answer: 'B',
    explanation: '28 May 1998 — Chagai tests made Pakistan a nuclear power. 1974 was India\'s Smiling Buddha test. Youm-e-Takbeer is commemorated annually.',
    topic: 'modern_history',
    difficulty: 'easy',
    type: 'most_important',
  },
  {
    question: 'The largest province of Pakistan by area is:',
    option_a: 'Punjab',
    option_b: 'Sindh',
    option_c: 'Balochistan',
    option_d: 'KPK',
    correct_answer: 'C',
    explanation: 'Balochistan ≈ 44% of Pakistan\'s land area though smallest by population. Punjab is largest by population and economy.',
    topic: 'geography',
    difficulty: 'easy',
    type: 'most_repeated',
  },
]

const ISSB_INTELLIGENCE: Row[] = [
  {
    question: 'Book : Author :: Painting : ?',
    option_a: 'Gallery',
    option_b: 'Artist',
    option_c: 'Canvas',
    option_d: 'Museum',
    correct_answer: 'B',
    explanation: 'Analogy: creator relationship. A book is created by an author; a painting is created by an artist. Gallery/museum are places, canvas is a medium.',
    topic: 'analogies',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'Find the odd one out: Circle, Square, Triangle, Cube',
    option_a: 'Circle',
    option_b: 'Square',
    option_c: 'Triangle',
    option_d: 'Cube',
    correct_answer: 'D',
    explanation: 'Circle, square, triangle are 2D shapes. Cube is 3D (a solid). ISSB intelligence tests often mix dimensions.',
    topic: 'odd_one_out',
    difficulty: 'easy',
    type: 'most_important',
  },
  {
    question: 'If CLOUD is coded as DMPVE, then RAIN is coded as:',
    option_a: 'SBJO',
    option_b: 'QZHM',
    option_c: 'SBKO',
    option_d: 'TCKP',
    correct_answer: 'A',
    explanation: 'Each letter +1: R→S, A→B, I→J, N→O. Pattern coding (+1 shift) is the most common ISSB coding rule.',
    topic: 'letter_coding',
    difficulty: 'medium',
    type: 'most_repeated',
  },
  {
    question: 'Complete the series: AZ, BY, CX, ?',
    option_a: 'DW',
    option_b: 'EV',
    option_c: 'DU',
    option_d: 'DX',
    correct_answer: 'A',
    explanation: 'First letters ascend A,B,C,D; second letters descend Z,Y,X,W → DW. Watch both columns in alphabet series.',
    topic: 'letter_series',
    difficulty: 'medium',
    type: 'practice',
  },
  {
    question: 'A is B\'s brother. C is A\'s mother. D is C\'s father. How is B related to D?',
    option_a: 'Granddaughter/Grandson',
    option_b: 'Daughter/Son',
    option_c: 'Sister',
    option_d: 'Cannot determine',
    correct_answer: 'A',
    explanation: 'C is mother of A and B (siblings). D is C\'s father → D is grandfather of B. Blood relation questions need a quick family tree sketch.',
    topic: 'blood_relations',
    difficulty: 'hard',
    type: 'most_important',
  },
  {
    question: 'Which figure completes the pattern: ▲, ▲▲, ▲▲▲, ?',
    option_a: '▲▲',
    option_b: '▲▲▲▲',
    option_c: '▲▲▲▲▲',
    option_d: '▲▼▲',
    correct_answer: 'B',
    explanation: 'Simple counting pattern: 1, 2, 3 triangles → next is 4. ISSB non-verbal items often use elementary progressions.',
    topic: 'pattern_recognition',
    difficulty: 'easy',
    type: 'practice',
  },
  {
    question: 'If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are definitely:',
    option_a: 'Lazzies',
    option_b: 'Not Lazzies',
    option_c: 'Razzies only',
    option_d: 'None of these',
    correct_answer: 'A',
    explanation: 'Syllogism: Bloops ⊂ Razzies ⊂ Lazzies → Bloops ⊂ Lazzies. Transitive property — common in logical reasoning sections.',
    topic: 'syllogisms',
    difficulty: 'medium',
    type: 'most_repeated',
  },
  {
    question: 'Military : Soldier :: Hospital : ?',
    option_a: 'Patient',
    option_b: 'Doctor',
    option_c: 'Medicine',
    option_d: 'Nurse',
    correct_answer: 'B',
    explanation: 'Functional analogy: primary professional in the institution. Soldier serves in military; doctor works in hospital. Patient is recipient, not professional role.',
    topic: 'analogies',
    difficulty: 'easy',
    type: 'most_repeated',
  },
  {
    question: 'Pointing to a photo, Ali said "He is the only son of my mother\'s mother." Who is in the photo?',
    option_a: 'Ali\'s uncle',
    option_b: 'Ali\'s brother',
    option_c: 'Ali himself',
    option_d: 'Ali\'s father',
    correct_answer: 'A',
    explanation: 'Mother\'s mother = maternal grandmother. Her only son = Ali\'s maternal uncle (mamoo). Classic ISSB blood-relation phrasing.',
    topic: 'blood_relations',
    difficulty: 'hard',
    type: 'most_important',
  },
  {
    question: 'Which number replaces ?: 3, 9, 27, ?, 243',
    option_a: '54',
    option_b: '72',
    option_c: '81',
    option_d: '90',
    correct_answer: 'C',
    explanation: 'Geometric series ×3 each step: 27×3 = 81. Check 81×3 = 243 confirms. Always verify with the next term.',
    topic: 'number_series',
    difficulty: 'easy',
    type: 'practice',
  },
]

const BANKS: [string, Row[]][] = [
  ['issb_english', ISSB_ENGLISH],
  ['issb_mathematics', ISSB_MATHEMATICS],
  ['issb_general_knowledge', ISSB_GK],
  ['issb_pakistan_affairs', ISSB_PAKISTAN],
  ['issb_intelligence', ISSB_INTELLIGENCE],
]

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY
  if (!url || !key) {
    console.error('Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY')
    process.exit(1)
  }
  const supabase = createClient(url, key)
  for (const [table, rows] of BANKS) {
    const { error } = await supabase.from(table).insert(rows)
    if (error) {
      console.error(`Failed ${table}:`, error.message)
      process.exit(1)
    }
    console.log(`Inserted ${rows.length} into ${table}`)
  }
  console.log('ISSB seed complete — 50 quality MCQs with explanations.')
}

main()
