import { EXAM_SITEMAP_LASTMOD, BASE_URL } from '@/lib/seo/sitemap-builders'
import { SITEMAP_XML_HEADERS } from '@/lib/seo/sitemap-xml'

/** Sitemap index — segments are generated by app/sitemap.ts via generateSitemaps(). */
export function GET() {
  const segments = ['core', 'exams', 'modes', 'sets'] as const
  const body = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${segments
  .map(
    (id) => `  <sitemap>
    <loc>${BASE_URL}/sitemap/${id}.xml</loc>
    <lastmod>${EXAM_SITEMAP_LASTMOD}</lastmod>
  </sitemap>`,
  )
  .join('\n')}
</sitemapindex>`

  return new Response(body, { headers: SITEMAP_XML_HEADERS })
}
